sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: UGnw6zjCN21EX2HzKzW6cuNU2WiHxMc8NyeFmkZEsttLKynw+cV8QkmIEje4H9hJfokTi7VGvaXlpgMx+qa7Z0XgA3SPuBZF+CM1x129+DCgZWikwEPN/iIkojXF0Qc0QtuttdoDutR1AVIkh2TwRVkhVkuBJ0aRaxxD5RnM5Yd8tWpx1hXTul4yk2cZ5BLpFGUgevYxYWhWblJ3K/dTdoN7TeW98gaEpP5LW62zlOMmcTMOm2YUDv7zyQCT1OdS5JqS8+vFME9SgcJbd5GxmMnvw+neUs+XjbNwaeX82s8EFN+Xwwi9VuX0TCo1JUj7bsR0qWVjcg5lRKLPWdI+NphBqFv5uLyPwFB4a50tTyTwCDAF080cmX9Ujv/mSKntKZWd/fhZcKYucE5UscNIswr/pwGqqmHPrSnW7nHJJfJOVXEZZlqjzJfo+kWi62ncQlw1K6urCwKOlHb8C1SpUqS2KTBAtLVAaU1bz/y3pCUlLKEHQ+xHpruVzuEgGgEizmkiG7mQinoGW85ptkSYvKdQ1/FIkmss19xgdDFPMtWyWnQK/03eHhJx6KovR2ffjQdkmgphukfWIfQjybvr+sv2vGL8GfbXWjAtOTJmxcHJeUU1AqGgxk4Fs0FNTWlI8qvQpdGe7/ZcAaZSD7RCu8e4KWp/4mYEk02WsX9Cyf4=
  - secure: NjZR+1wbmDFMgn7o/4dnK/T+fpFJcXewD9DMgerQE9FqNea4ZtuU/5s0XJXRxcpokhO+I7Nncln4Z+qTs8HObW9aG09wz7iHI4Yuy2EyLDyRh91nler4k6r3id+WSZgPy1cXXuljXe09nh172M7q9CEpH8WRHqym6oOjcdB5otHmmYuUpKqEvLe8PVsWd+swFFYb8P5Dm4ETXL8y46K7c4sdDyu/nbqx2zj4JeoOHq2aB9unJBgxOK6RoQh7SwpWvXTxw16yEz24KQkHMFJy/ooF3ILThGDQzFxAKIFXudQOAYmwlvjb+OT/+wVfSc3IlDy6M0AGSqFqLT01I9HC9LRkprSuHdT+pXtUWOWrNoEFT83+wTKRDm6p50d66fYPrL5QImdCc0p9qlUyIrZTiZuhPofsZly/214XTrkwgyk182OUdobvVn5c6OQRuOYCiBou8TV4Dsk02pxsj9b2eORxpqti4pr8OQdnqyCIBozsHiZR+DA0RTGXAwuaVAqvHr1GzzbasHC2iieVD7Or+hGWdSo06aZE27mQb0HxViaVDGlXPLJEo5miktQQQFQWUmAO4kR/uuBrvm1LAZu3qTrEBA4ZJ8XAyb+4lgT+szbx8b/0g4Zh0T4kR1J3nxultQAxJLaxOAMm48owRuUnBhfplnDGmMo44uoQc6E0UAY=
  - secure: OZOh04VIHSWTwZCF1K9IaxPFrx229cnzxuXbTyAR/nE5jLan2YQEwJtOpjFIHCrDzfsTLFGX15iG9JhN5aIuzAFXd875yGcVlOsDsb6n/P8e6VQUXMaQHW5l4y9rECl8Utfgvfweja/m1/k338tE2Ym0N/lvpkRC9sXghC9LeY4VfIfEGzgt/DXuzckQHN4CADVPLWmhcYVuXrGW1oojEJX2Adrh8c1MRFIz3xr+7+SKpOY7k8T9tukcMVqOio9ToMHxT5m+OoHB+PO17YLWFY0At2AybZsgiZ054auwT+PX8T8PR0nivTevH8FutIxUlAoTaw2d76v8ZvMbyGtY9uQTjPHFfKmPcdp2GcVOW3UPaKC1/7nHW0jrwXSGjzUhk4D55lMjFIMNYvBVH5BMQf3YLhP3SEdWUuSbjKhlDyiTnd93pYOapv+olu2b+dEyRJz74gLlx3FzXnD7rziQ49gUfeQdxK0WLAkvIPOKS5JNMk7iJ3eMraiacIoIeK9STZwjqjh2mhWAJEXmY6p8d6nFPIIIbU2PNGSBjAstV20frH3AGdOKL3p9gsNlr8gUKU/aizCm+uL+KGbZ7bIYLY68LDJvHTjCsWoQc9iygp0xJwyQAlgMz4yNsbUiz9T8SCngB4NmYOyTna+Rk4f47neyegKANpRkGPMOD5XYFxw=
  - secure: XzXirqtC2MEbUUooCkR2p9aqeH6rT9opy4LcZRIbQWdEiAPpTx6Ey12iIhrCsgie1zgxKdxXB+12k1K4cHb2PpWO08j7eUVQ9+When5rd5HKSkT6jpUljs/EOQT2OqWXoq4TSEtvSlnUqug1XIBRrMip9ApRbRc3lU65bsmVfCxUgqSStbER5k9pDQ8dNKWUEo6z4eKxlNFeL8hgWwYAmNjX8+3ON7S4XiqpNbB68eX8uOygmKiTDdtNUvdOCMdAk0upeg3GYNeC/TSLnB8cDl5Y0UfpA4CxpusqDac/fclVbR5CZXmUZaRH21UIrNq0oLmwThAbjJFmTJzP4NNmocMVM/4D7Bs1p5j1UBJb7T0+/V6xjGWhXzshLpkJkET/VCBOv/cMOlVVRPCb41XQ3XvgFOhRtWp1A6Hf16ObIYxTZu4cVfKQHZHYwJXupepTUsibN08isVakGTEU1XOtHHnTU145Oxk7FLSBZ35ar4RWFOd5UiEhT9KquDD5bLs9UTNgwjhYkKF6DkE2Jpbuvmgf5YiDloSKuEIIfbO6ak01Zggf8GjL9dJoc9IK5uZBG32f8DTbXoDgr7m4XDDd27ikOKGPKKpFrJ34xhPFbwxNCsyUb/agamGPLw5s110K4qqwbIIeQ0ssPo6HeO7fYMWds37j7mUUY1YRNntvA0U=
