language: node_js
sudo: false
node_js: stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- wct --plugin sauce --skip-plugin local
env:
  global:
  - secure: D20FMq3CaaHJcBRHcX/ssr8lQdta92rp8aJ1407kl9raKyn0xRhaOYvtYUcfc12CQlrc0xS+9hVGfBbsWHe1ob9wvZWVFEy1uCHeAbRXiJsXmixKEdG4WIQDb134O24G9KwcVDwxdc6n/FUkHuvEGnEFZCE+RjSVyIAo7Thn52yKYIhatTt7AP2U02L/p5G9B9N3Ag8isPUWyelURWN06dWFvbCVMV+BBGfrffQMamZydjifQHUYX0KQdFFnQLNW/4JsGnVu4Epsn8NaboI/Ln/qfoNnEhz83oQDJ1aX5h2TzRTYbAYmhjgAgafmgill19CxwDPLU/Xm0dAfAwo1HdmL1QudJbBZoY+jEPsPrA3NfK/qkOrW2fp6nZS/Xhfstu7GjDi1bL/BL6HEJ9aywIhlC+dbd8ezxhnSt3f1M5inB+Hy4BetYG76r3f4Ge8KhJyTr+Sy3W0nK+hFSG+EBzJkvS/VKQVtFmXRVkgLkx5Q8PCKcnaWhW6laV9/sIKRPb/VhKOARmkJPpxdiVc2tgZipM1y9zMVAgI0xjyOh1IPnGc3qtx1E5dlAwjqpsgqZ5bugsGpMZW9v6c5mvbDUitetkReZ1Y/JLdi5Ghz9fsepbh3jBkVjcAsbE9fOajH6AAn2TJEXsYQk9q+IGCDEMCriquGZZGHbxmc7oZvp0s=
  - secure: GqRiiX4SIza8OIkvYwAUNDbgap0N0FDj2FY3D/1NEu1UW5UyTECkEebAEYF12v8vl6oFe5aURirt8MJdy7jxkpRzhGnncPldAPAc6ffCRg5LBfT0wqY4evS0OPDAxVPMOkA++mUGVbT3fVDHMQ1xwvHTQaybUpfjiBkgyeATRtfLgyHDxGPAAd3LVAXFofZwacXGht26uVAUqCB8PRX0k+qBeMTsVHvRXoINy+RnkOOwQ/BxJF7y0pX39O/ELIEmEDF8ChkRlzMAbDbjtrRRfUz4ktXn2qBNJNzLISmQAs4OtktFpaf4Gxal1psuNXzGD6F+4OspAKYEcp4G6hmXpnaltr3xSG9NyTlcl5xK13inu1XF4u+jHcrc53yttvMN4FJQOgFS9hekjupnm+qzCsV9lLOCg6sB3/dy6wsD5ge7N5sAgwOab4+pey5+z1tfRwAc3UE51MiMhZl+2bWu8QMkPhf8nxhb6tSRxi0w+suQsgRYWWnKACoZBXfCuBTDyCFtbIVgV6D0YlZJFhD/2NH/yNtHInWJxewhDKCnIR4xsdFhPNElLuHU0WIz5yPtY71URvihflpyeyZgK01WAmCjQpKe9QZ425h9KTZU3fNuDn0EY6C3tCVsBtCX96a8+3VWI0KwZFlx/biVve8Wz6jUnf7UhESEgMQzJd7ANFE=
